# basic configuration for a reinforcement learning agent
# that mirrors "Playing Atari with Deep Reinforcement Learning"

# Environment parameters
env:
  env_name: "SuperMarioBrosRandomStages-v0"
  # If true, we'll give reward equal to score delta.
  use_score: true
  max_steps_per_episode: 10000
  render: true
  num_episodes: 1000

# Device configuration
device: mps

agent:
  # Learning parameters
  gamma: 0.99
  epsilon: 1.0
  epsilon_min: 0.02
  epsilon_decay: 0.9995
  learning_rate: 0.0001
  batch_size: 128
  memory_size: 100000
  loss: "smooth_l1" 
  clip_gradients: 0.15
  optimizer: "adam"         # Optimizer for training the neural network
  
  # Action parameters
  action_repeat_steps: 4
  replay_every_n_steps: 256
  target_update_frequency: 4096

  state:
    # Input shape for the NN will be (`stack_frames`, 84, 84)
    resize_shape: [84, 84]
    grayscale: true
    normalize: true
    stack_frames: 4

  network:
    dqn:
      hidden_layers: [256] # Hidden layers for the neural network
      activation: "ReLU"   # Non-linear
#save_model_freq: 100       # Episodes between saving model checkpoints
#log_interval: 10           # Episodes between logging progress