# basic configuration for a reinforcement learning agent
# that mirrors "Playing Atari with Deep Reinforcement Learning"


# Environment parameters
env:
  env_name: "SuperMarioBros-v0"
  # If true, we'll give reward equal to score delta.
  use_score: true
  max_steps_per_episode: 3000
  render: true
  num_episodes: 100

# Device configuration
device: mps

agent:
  # Used for checkpointing.
  name: "basic_1-1_stage"

  # Learning parameters
  gamma: 0.99
  epsilon: 1.0
  epsilon_min: 0.02
  epsilon_decay: 0.995
  learning_rate: 0.0001
  batch_size: 32
  memory_size: 1000
  loss: "smooth_l1"
  clip_gradients: 0.15
  optimizer: "adam"         # Optimizer for training the neural network
  action_selection: "max"
  
  # Action parameters
  action_repeat_steps: 4 # No action repeat for this agent
  replay_every_n_steps: 16
  target_update_frequency: 2048

  state:
    # Input shape for the NN will be (`stack_frames`, 84, 84)
    resize_shape: [84, 84]
    grayscale: true
    normalize: true
    stack_frames: 8

  network:
    dqn:
      hidden_layers: [256] # Hidden layers for the neural network
      activation: "ReLU"   # Non-linear

#log_interval: 10           # Episodes between logging progress