device: mps

seed: 42

env:
  env_name: CartPole-v1
  env_wrappers:
    - CaptureRenderFrameEnv
    - PreprocessFrameEnv
    - HistoryEnv
  ObservationWrapper:
    input: dense
  CaptureRenderFrameEnv:
    mode: replace
  PreprocessFrameEnv:
    resize_shape: [84, 84]
    grayscale: true
    normalize: true
  HistoryEnv:
    history_length: 4

  env_action_labels: [LEFT, RIGHT]
  num_episodes: 4000
  max_steps_per_episode: 500
  headless: false

agent:
  name: cartpole_frame
  gamma: 0.99

  epsilon: 0.5
  epsilon_min: 0.05
  epsilon_linear_decay: 0.00005

  batch_size: 16
  min_memory_size: 16
  loss: mse
  clip_gradients: 50.0

  # Optimizer settings
  optimizer: adam
  learning_rate: 0.001
  lr_scheduler:
    type: lr_scheduler.LinearLR
    args:
      start_factor: 1
      end_factor: 0.2
      total_iters: 25000

  action_selection: max
  double_dqn: true

  replay_buffer:
    type: prioritized
    size: 5000
    alpha: 0.5
    beta: 0.5
    beta_annealing_steps: 30000

  replay_every_n_steps: 1
  replays_until_target_update: 100

  network:
    dueling_dqn:
      convolution:
        type: 2d
        kernel_sizes: [8, 6, 4]
        channels: [16, 32, 64]
        strides: [1, 2, 2]

      value_hidden_layers: [32, 32]
      advantage_hidden_layers: [32, 32]