# basic configuration for a reinforcement learning agent
# that mirrors Playing Atari with Deep Reinforcement Learning

# Environment parameters
env:
  env_name: SuperMarioBros-v0
  use_score: true
  max_steps_per_episode: 3000
  render: true
  num_episodes: 1000

# Device configuration
device: mps

agent:
  name: experiment_1_agent_softmax_0_2

  # Learning parameters
  gamma: 0.99
  epsilon: 1.0
  epsilon_min: 0.02
  epsilon_decay: 0.9995
  learning_rate: 0.0001
  batch_size: 64
  memory_size: 1000000
  loss: smooth_l1
  clip_gradients: 0.15
  optimizer: adam
  action_selection: softmax
  action_selection_temperature: 0.1
  
  # Action parameters
  action_repeat_steps: 4
  replay_every_n_steps: 16
  target_update_frequency: 2048

  state:
    resize_shape: [128, 128]
    grayscale: true
    normalize: true
    stack_frames: 8

  network:
    dqn:
      hidden_layers: [256, 128]
