device: mps

seed: 42
execution_mode: synchronous

env:
  env_name: "LunarLander-v3"
  env_kwargs:
    continuous: False
    gravity: -10.0
    enable_wind: False
    wind_power: 15.0
    turbulence_power: 1.5
  env_wrappers:
    #- PreprocessFrameEnv
    # - HistoryEnv
    - CaptureRenderFrameEnv
    #- ReturnActionEnv
    
  ObservationWrapper:
    input: dense
  CaptureRenderFrameEnv:
    mode: capture  # Options: 'capture', 'replace'
  PreprocessFrameEnv:
    resize_shape: [84, 84]
    grayscale: true
    normalize: true
  HistoryEnv:
    history_length: 4
  num_envs: 32

  env_action_labels: [NOOP, LEFT, MAIN, RIGHT]
  num_steps: 9_500_000
  headless: false

agent:
  type: policy
  name: lander_a2c_bis
  gamma: 0.99

  loss: mse

  # Optimizer settings
  optimizer: adam
  clip_grandients: 10.0
  learning_rate: 0.0003
  entropy_coeff: 0.1
  lr_scheduler:
    type: lr_scheduler.LinearLR
    args:
      start_factor: 1
      end_factor: 0.2
      total_iters: 100_000

  batch_size: 128
  action_selection: max

  checkpoint_every_n_replays: 100

  network:
    use_residual: true
    torso:
      hidden_layers: [32, 32]
    actor:
      hidden_layers: [32, 32]
    critic:
      hidden_layers: [32, 32]

