device: mps

env:
  env_name: ALE/Pong-v5
  env_action_labels: [NOOP, FIRE, RIGHT, LEFT, RIGHTFIRE, LEFTFIRE]
  num_episodes: 250000
  max_num_steps: 4
  max_steps_per_episode: 3000
  use_score: false

agent:
  name: test_baseline
  # Minimal agent settings for baseline
  gamma: 0.99
  epsilon: 0.9
  epsilon_min: 0.1
  epsilon_decay: 0.999
  learning_rate: 0.00005
  batch_size: 64
  memory_size: 1000000
  min_memory_size: 1000
  memory_selection: uniform
  loss: huber
  clip_gradients: 10.0
  optimizer: adam
  action_selection: max

  # Action parameters
  action_repeat_steps: 4
  replay_every_n_steps: 8
  target_update_freq: 10000

  state:
    resize_shape: [84, 84]
    grayscale: true
    normalize: true
    stack_frames: 8

  network:
    dqn:
      hidden_layers: [512, 512]

