device: mps

env:
  env_name: CartPole-v1
  env_action_labels: [LEFT, RIGHT]
  num_episodes: 100000
  max_steps_per_episode: 500
  use_score: false
  headless: true

agent:
  name: test_cartpole_v8
  # Minimal agent settings for baseline
  gamma: 0.99
  epsilon: 0.8
  epsilon_min: 0.1
  epsilon_decay: 0.9999
  learning_rate: 0.00001
  batch_size: 32
  memory_size: 1000000
  min_memory_size: 1000
  memory_selection: uniform
  loss: huber
  clip_gradients: 5.0
  optimizer: adam
  action_selection: max

  # Action parameters
  action_repeat_steps: 0
  replay_every_n_steps: 1
  replays_until_target_update: 3000


  state:
    resize_shape: [96, 96]
    grayscale: true
    normalize: true
    stack_frames: 4

  network:
    dqn:
      hidden_layers: [512, 256]

