device: mps

seed: 42
execution_mode: synchronous

env:
  env_name: "LunarLander-v3"
  env_kwargs:
    continuous: False
    gravity: -10.0
    enable_wind: False
    wind_power: 15.0
    turbulence_power: 1.5
  env_wrappers:
    - HistoryEnv
    #- CaptureRenderFrameEnv
    #- ReturnActionEnv
    
  ObservationWrapper:
    input: dense
  CaptureRenderFrameEnv:
    mode: capture  # Options: 'capture', 'replace'
  HistoryEnv:
    history_length: 8
  num_envs: 8

  env_action_labels: [NOOP, LEFT, MAIN, RIGHT]
  num_steps: 200_000
  headless: true

agent:
  name: lander_clipped_grad
  gamma: 1

  batch_size: 512
  min_memory_size: 512
  loss: mse

  # Optimizer settings
  optimizer: adam
  learning_rate: 0.001
  lr_scheduler:
    type: lr_scheduler.LinearLR
    args:
      start_factor: 1
      end_factor: 0.2
      total_iters: 100_000

  clip_gradients: 40.0

  action_selection: max
  epsilon: 0.9
  epsilon_linear_decay: 0.0001
  epsilon_min: 0.05

  replay_buffer:
    type: uniform
    size: 100_000

  replays_until_target_update: 5
  checkpoint_every_n_replays: 100

  network:
    dqn:
      hidden_layers: [32,32,32]

